### ISSUE TITLE
Modifier un évènement donne une erreur 500

### ISSUE THREAD

**Issue by charles-zablit** [nantral-platform/nantralPlatform#553]
Quand on modifie un event, on obtient une erreur 500.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/app/apps/event/views.py", line 95, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 126, in form_valid
    return super().form_valid(form)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 57, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 116, in get_success_url
    url = self.object.get_absolute_url()
TypeError: 'str' object is not callable
```

**Comment by charles-zablit** [comment]
On ne peut pas définir les `get_absolute_url` des models comme des properties, certaines vues génériques de Django s'attendent à avoir une méthode, d'où le `TypeError: 'str' object is not callable` du trace back.
